### ISSUE TITLE
Code accessibility issue

### ISSUE THREAD

**Issue by JunYang2021** [BioNet-XMU/DeepION#1]
Hi, I want to download and run the code of DeepION. But it seems there are only two python files in the repository(run.py and augmentation.py). The other files are probably not public.
Thank you very much for your time and effort in maintaining this project. Looking forward to your response.

**Comment by BioNet-XMU** [comment]
The missing files had been uploaded to DeepION directory.

Jun Yang ***@***.***>于2024年2月27日 周二10:22写道：
